# Generated by Django 4.2.6 on 2023-11-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
    ]
